### ISSUE TITLE
Can just preview in Sublime Text 3 ?

### ISSUE THREAD

**Issue by livem** [hlfcoding/sublime-mermaid#3]
Hi, this is a good job for Sublime Text 3.

But from the Command Palette: Mermaid: View In Browser, can preview in browser.

Is it possible to be preview in Sublime Text 3 like Markdown ?

Thanks.

**Comment by trippingbillies41** [comment]
Just learned about Mermaid, also looking for this feature.

**Comment by chief-wrench** [comment]
have my upvote

**Comment by hlfcoding** [comment]
Thanks for your interest! I agree that's a nice enhancement I overlooked. Sadly, if not obvious, I'm no longer maintaining this package, mainly because I no longer want to use Sublime. I wish everyone here the best if they decide to fork and continue this package, and I'd be happy to help with any transition.
